INSERT INTO EVENT_BATCH_CONFIG(JOB_ID,JOB_NAME,CRON_TRIGGER,BATCH_ENPOINT,USERNAME,PASSWORD_KEY) VALUES ("123","SAMPLE_JOB","5","batchEndPoint","userName","password");
INSERT INTO EVENT_BATCH_JOB_PARAMS(JOB_ID,JOB_PARAM_KEY,JOB_PARAM_VALUE) VALUES ("123","date",current_timestamp);
INSERT INTO EVENT_BATCH_JOB_PARAMS(JOB_ID,JOB_PARAM_KEY,JOB_PARAM_VALUE) VALUES ("123","name","BatchJobTest1");

--CREATE SEQUENCE EVENT_WORKFLOW_BATC_SEQ START WITH 1 INCREMENT BY 1;